site_name: baradlab/michigan_tutorial
site_url: https://baradlab.com/michigan_tutorial
site_author: baradlab
site_description: >-
  Segmentation and modeling tutorial for U Michigan
repo_name: baradlab/michigan_tutorial
repo_url: https://github.com/baradlab/michigan_tutorial
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 baradlab


# Custom navigation can be specified
nav:
  - Overview: index.md
  - Setup Steps: setup.md
  - Membrain-Seg Segmentation: membrain-seg.md
  - Dragonfly Segmentation: dragonfly.md
  - Surface Morphometrics: morphometrics.md

theme:
  icon:
    logo: material/cube-outline
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: slate)"
      scheme: slate
      primary: blue
      accent: blue

  features:
    - navigation.instant
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.tabs.link

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search